version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      cargo-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/function-cfgd"
      - "/tests/e2e/cli"
    schedule:
      interval: "weekly"
    groups:
      docker:
        patterns: ["*"]
        update-types: ["minor", "patch"]
