FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN adduser --disabled-password --gecos "" --uid 1000 cfgd

ARG TARGETOS=linux
ARG TARGETARCH
COPY ${TARGETOS}/${TARGETARCH}/cfgd-operator /usr/local/bin/cfgd-operator

USER cfgd
WORKDIR /home/cfgd

ENTRYPOINT ["cfgd-operator"]
