use super::*;
use cfgd_core::output::{Doc, Printer, Role};

pub fn cmd_workflow_generate(cli: &Cli, v2_printer: &Printer, force: bool) -> anyhow::Result<()> {
    let config_dir = config_dir(cli);
    let workflow_dir = config_dir.join(".github").join("workflows");
    let workflow_path = workflow_dir.join("cfgd-release.yml");

    // Scan for profiles and modules
    let profile_names = scan_profile_names(&config_dir.join("profiles"))?;
    let module_names = scan_module_names(&config_dir.join("modules"))?;

    let default_branch =
        cfgd_core::detect_default_branch(&config_dir).unwrap_or_else(|| "master".to_string());

    if profile_names.is_empty() && module_names.is_empty() {
        v2_printer.emit(
            Doc::new()
                .status(
                    Role::Warn,
                    "No profiles or modules found — nothing to generate",
                )
                .with_data(serde_json::json!({
                    "path": workflow_path.display().to_string(),
                    "profiles": Vec::<String>::new(),
                    "modules": Vec::<String>::new(),
                    "skipped": true,
                })),
        );
        return Ok(());
    }

    // Check for existing file
    if workflow_path.exists()
        && !force
        && !v2_printer
            .prompt_confirm(&format!(
                "Workflow already exists at {} — overwrite?",
                workflow_path.display()
            ))
            .unwrap_or(false)
    {
        v2_printer.emit(
            Doc::new()
                .status(Role::Info, "Skipped workflow generation")
                .with_data(serde_json::json!({
                    "path": workflow_path.display().to_string(),
                    "skipped": true,
                    "profiles": &profile_names,
                    "modules": &module_names,
                })),
        );
        return Ok(());
    }

    let yaml = generate_release_workflow_yaml(&module_names, &profile_names, &default_branch);

    std::fs::create_dir_all(&workflow_dir).map_err(|e| {
        v2_printer.emit(cfgd_core::output::error_doc(
            &workflow_path.display().to_string(),
            "write_failed",
            format!("failed to create workflow directory: {}", e),
            serde_json::json!({ "path": workflow_path.display().to_string() }),
        ));
        anyhow::anyhow!("failed to create workflow directory: {}", e)
    })?;
    cfgd_core::atomic_write_str(&workflow_path, &yaml).map_err(|e| {
        v2_printer.emit(cfgd_core::output::error_doc(
            &workflow_path.display().to_string(),
            "write_failed",
            format!("failed to write workflow file: {}", e),
            serde_json::json!({ "path": workflow_path.display().to_string() }),
        ));
        anyhow::anyhow!("failed to write workflow file: {}", e)
    })?;

    v2_printer.emit(
        Doc::new()
            .status(
                Role::Ok,
                format!("Generated release workflow at {}", workflow_path.display()),
            )
            .kv("Modules", module_names.len().to_string())
            .kv("Profiles", profile_names.len().to_string())
            .with_data(serde_json::json!({
                "path": workflow_path.display().to_string(),
                "profiles": &profile_names,
                "modules": &module_names,
            })),
    );

    Ok(())
}

pub(super) fn generate_release_workflow_yaml(
    modules: &[String],
    profiles: &[String],
    default_branch: &str,
) -> String {
    let mut yaml = String::new();
    let has_targets = !modules.is_empty() || !profiles.is_empty();

    // Header
    yaml.push_str(&format!(
        "# Auto-generated by cfgd — manages release tagging for modules and profiles.\n\
         # Regenerate with: cfgd workflow generate --force\n\
         name: cfgd Release\n\
         \n\
         on:\n\
         \x20 push:\n\
         \x20   branches: [{}]\n",
        default_branch,
    ));

    if has_targets {
        yaml.push_str("    paths:\n");
        for m in modules {
            yaml.push_str(&format!("      - 'modules/{}/**'\n", m));
        }
        for p in profiles {
            yaml.push_str(&format!("      - 'profiles/{}.yaml'\n", p));
            yaml.push_str(&format!("      - 'profiles/{}.yml'\n", p));
        }
    } else {
        yaml.push_str(
            "    # paths: (auto-populated when modules/profiles are created)\n\
             \x20   #   - 'modules/<name>/**'\n\
             \x20   #   - 'profiles/<name>.yaml'\n",
        );
    }

    yaml.push_str(
        "\n\
         permissions:\n\
         \x20 contents: write\n\
         \n\
         jobs:\n",
    );

    if !has_targets {
        yaml.push_str(
            "  # Jobs are auto-generated when modules or profiles are created.\n\
             \x20 # Run `cfgd workflow generate --force` to regenerate manually.\n\
             \x20 placeholder:\n\
             \x20   runs-on: ubuntu-latest\n\
             \x20   steps:\n\
             \x20     - run: echo \"No modules or profiles to tag yet.\"\n",
        );
        return yaml;
    }

    // Detect changes job
    yaml.push_str(
        "\x20 detect-changes:\n\
         \x20   runs-on: ubuntu-latest\n\
         \x20   outputs:\n",
    );
    for m in modules {
        let safe = m.replace('-', "_");
        yaml.push_str(&format!(
            "      module_{}: ${{{{ steps.changes.outputs.module_{} }}}}\n",
            safe, safe
        ));
    }
    for p in profiles {
        let safe = p.replace('-', "_");
        yaml.push_str(&format!(
            "      profile_{}: ${{{{ steps.changes.outputs.profile_{} }}}}\n",
            safe, safe
        ));
    }

    yaml.push_str(
        "\x20   steps:\n\
         \x20     - uses: actions/checkout@v4\n\
         \x20       with:\n\
         \x20         fetch-depth: 0\n\
         \x20     - id: changes\n\
         \x20       run: |\n\
         \x20         if git rev-parse HEAD~1 >/dev/null 2>&1; then\n\
         \x20           CHANGED=$(git diff --name-only HEAD~1 HEAD)\n\
         \x20         else\n\
         \x20           CHANGED=$(git diff-tree --no-commit-id --name-only -r HEAD)\n\
         \x20         fi\n",
    );

    for m in modules {
        let safe = m.replace('-', "_");
        yaml.push_str(&format!(
            "          if echo \"$CHANGED\" | grep -q '^modules/{}/'; then\n\
             \x20           echo \"module_{}=true\" >> $GITHUB_OUTPUT\n\
             \x20         else\n\
             \x20           echo \"module_{}=false\" >> $GITHUB_OUTPUT\n\
             \x20         fi\n",
            m, safe, safe
        ));
    }
    for p in profiles {
        let safe = p.replace('-', "_");
        yaml.push_str(&format!(
            "          if echo \"$CHANGED\" | grep -q '^profiles/{}\\.'; then\n\
             \x20           echo \"profile_{}=true\" >> $GITHUB_OUTPUT\n\
             \x20         else\n\
             \x20           echo \"profile_{}=false\" >> $GITHUB_OUTPUT\n\
             \x20         fi\n",
            p, safe, safe
        ));
    }

    // Tag modules job
    if !modules.is_empty() {
        yaml.push_str(
            "\n\
             \x20 tag-modules:\n\
             \x20   runs-on: ubuntu-latest\n\
             \x20   needs: detect-changes\n\
             \x20   strategy:\n\
             \x20     matrix:\n\
             \x20       include:\n",
        );
        for m in modules {
            let safe = m.replace('-', "_");
            yaml.push_str(&format!(
                "          - name: {}\n\
                 \x20           changed: ${{{{ needs.detect-changes.outputs.module_{} }}}}\n",
                m, safe
            ));
        }
        yaml.push_str(
            "\x20   steps:\n\
             \x20     - uses: actions/checkout@v4\n\
             \x20       if: matrix.changed == 'true'\n\
             \x20       with:\n\
             \x20         fetch-depth: 0\n\
             \x20     - name: Read module version\n\
             \x20       if: matrix.changed == 'true'\n\
             \x20       id: version\n\
             \x20       run: |\n\
             \x20         VERSION=$(grep -oP 'version:\\s*\"?\\K[^\"\\s]+' \"modules/${{ matrix.name }}/module.yaml\" || echo \"0.1.0\")\n\
             \x20         echo \"version=$VERSION\" >> $GITHUB_OUTPUT\n\
             \x20     - name: Tag module release\n\
             \x20       if: matrix.changed == 'true'\n\
             \x20       run: |\n\
             \x20         TAG=\"${{ matrix.name }}/v${{ steps.version.outputs.version }}\"\n\
             \x20         git tag -f \"$TAG\"\n\
             \x20         git push origin \"$TAG\" --force\n",
        );
    }

    // Tag profiles job
    if !profiles.is_empty() {
        yaml.push_str(
            "\n\
             \x20 tag-profiles:\n\
             \x20   runs-on: ubuntu-latest\n\
             \x20   needs: detect-changes\n\
             \x20   strategy:\n\
             \x20     matrix:\n\
             \x20       include:\n",
        );
        for p in profiles {
            let safe = p.replace('-', "_");
            yaml.push_str(&format!(
                "          - name: {}\n\
                 \x20           changed: ${{{{ needs.detect-changes.outputs.profile_{} }}}}\n",
                p, safe
            ));
        }
        yaml.push_str(
            "\x20   steps:\n\
             \x20     - uses: actions/checkout@v4\n\
             \x20       if: matrix.changed == 'true'\n\
             \x20       with:\n\
             \x20         fetch-depth: 0\n\
             \x20     - name: Tag profile release\n\
             \x20       if: matrix.changed == 'true'\n\
             \x20       run: |\n\
             \x20         DATE=$(date +%Y%m%d)\n\
             \x20         TAG=\"profile/${{ matrix.name }}/${DATE}\"\n\
             \x20         git tag -f \"$TAG\"\n\
             \x20         git push origin \"$TAG\" --force\n",
        );
    }

    yaml
}

pub(super) fn maybe_update_workflow(
    cli: &Cli,
    v2_printer: &cfgd_core::output::Printer,
) -> anyhow::Result<()> {
    let config_dir = config_dir(cli);
    init::regenerate_workflow(&config_dir, v2_printer)?;
    Ok(())
}
