{{- if .Values.deviceGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cfgd-operator.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cfgd-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.deviceGateway.port }}
      targetPort: gateway
      protocol: TCP
      name: http-gateway
  selector:
    {{- include "cfgd-operator.selectorLabels" . | nindent 4 }}
{{- end }}
