{{- if and .Values.deviceGateway.enabled .Values.deviceGateway.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cfgd-operator.fullname" . }}-gateway-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cfgd-operator.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.deviceGateway.persistence.storageClass }}
  storageClassName: {{ .Values.deviceGateway.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.deviceGateway.persistence.size }}
{{- end }}
