apiVersion: v2
name: cfgd
description: cfgd — declarative machine configuration management (operator + agent)
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - kubernetes
  - operator
  - config
  - gitops
  - crd
  - daemonset
home: https://github.com/tj-smith47/cfgd
icon: https://raw.githubusercontent.com/tj-smith47/cfgd/master/.github/gear.svg
maintainers:
  - name: cfgd
    url: https://github.com/tj-smith47/cfgd
