use super::{ResourceSchema, SchemaField};

pub(super) static SCHEMA_MODULE: ResourceSchema = ResourceSchema {
    name: "Module",
    api_version: cfgd_core::API_VERSION,
    kind: "Module",
    location: "modules/<name>/module.yaml",
    description: "Self-contained, portable configuration unit. Defines packages, files, and scripts with cross-platform resolution and dependency management.",
    fields: &[
        SchemaField {
            name: "depends",
            type_desc: "[]string",
            required: false,
            description: "Module dependencies (resolved via topological sort)",
            children: &[],
        },
        SchemaField {
            name: "packages",
            type_desc: "[]object",
            required: false,
            description: "Platform-agnostic package declarations",
            children: &[
                SchemaField {
                    name: "name",
                    type_desc: "string",
                    required: true,
                    description: "Canonical package name",
                    children: &[],
                },
                SchemaField {
                    name: "minVersion",
                    type_desc: "string",
                    required: false,
                    description: "Minimum required version (semver)",
                    children: &[],
                },
                SchemaField {
                    name: "prefer",
                    type_desc: "[]string",
                    required: false,
                    description: "Preferred package managers in order (e.g., [brew, apt, script])",
                    children: &[],
                },
                SchemaField {
                    name: "aliases",
                    type_desc: "map[string]string",
                    required: false,
                    description: "Manager-specific package names (e.g., {apt: fd-find})",
                    children: &[],
                },
                SchemaField {
                    name: "script",
                    type_desc: "string",
                    required: false,
                    description: "Inline install script or path (used when prefer includes 'script')",
                    children: &[],
                },
                SchemaField {
                    name: "platforms",
                    type_desc: "[]string",
                    required: false,
                    description: "Platform filter: linux, macos, freebsd, ubuntu, arch, x86_64, aarch64",
                    children: &[],
                },
            ],
        },
        SchemaField {
            name: "files",
            type_desc: "[]object",
            required: false,
            description: "Files to manage (local or git sources)",
            children: &[
                SchemaField {
                    name: "source",
                    type_desc: "string",
                    required: true,
                    description: "Source path (local relative or git URL with @tag, ?ref=, //subdir)",
                    children: &[],
                },
                SchemaField {
                    name: "target",
                    type_desc: "string",
                    required: true,
                    description: "Target path on the machine",
                    children: &[],
                },
            ],
        },
        SchemaField {
            name: "env",
            type_desc: "list[{name, value}]",
            required: false,
            description: "Environment variables merged with profile env (module wins on conflict by name)",
            children: &[],
        },
        SchemaField {
            name: "aliases",
            type_desc: "list[{name, command}]",
            required: false,
            description: "Shell aliases merged with profile aliases (module wins on conflict by name)",
            children: &[],
        },
        SchemaField {
            name: "scripts",
            type_desc: "object",
            required: false,
            description: "Lifecycle scripts",
            children: &[SchemaField {
                name: "postApply",
                type_desc: "[]string",
                required: false,
                description: "Scripts to run after module is applied",
                children: &[],
            }],
        },
    ],
};
