use super::{ResourceSchema, SchemaField};

pub(super) static SCHEMA_CONFIG: ResourceSchema = ResourceSchema {
    name: "CfgdConfig",
    api_version: cfgd_core::API_VERSION,
    kind: "Config",
    location: "cfgd.yaml",
    description: "Root configuration file for cfgd. Defines the active profile, origin, daemon settings, secrets backend, sources, theme, and module sources.",
    fields: &[
        SchemaField {
            name: "profile",
            type_desc: "string",
            required: true,
            description: "Active profile name for this machine",
            children: &[],
        },
        SchemaField {
            name: "origin",
            type_desc: "object | []object",
            required: false,
            description: "Git or server origin(s) for config syncing",
            children: &[
                SchemaField {
                    name: "type",
                    type_desc: "string",
                    required: true,
                    description: "Origin type: Git | Server",
                    children: &[],
                },
                SchemaField {
                    name: "url",
                    type_desc: "string",
                    required: true,
                    description: "Repository URL or server endpoint",
                    children: &[],
                },
                SchemaField {
                    name: "branch",
                    type_desc: "string",
                    required: false,
                    description: "Git branch (default: master)",
                    children: &[],
                },
                SchemaField {
                    name: "auth",
                    type_desc: "string",
                    required: false,
                    description: "Auth method for server origins (e.g., device-flow)",
                    children: &[],
                },
            ],
        },
        SchemaField {
            name: "daemon",
            type_desc: "object",
            required: false,
            description: "Daemon configuration",
            children: &[
                SchemaField {
                    name: "enabled",
                    type_desc: "bool",
                    required: false,
                    description: "Enable the daemon (default: false)",
                    children: &[],
                },
                SchemaField {
                    name: "reconcile",
                    type_desc: "object",
                    required: false,
                    description: "Reconciliation settings",
                    children: &[
                        SchemaField {
                            name: "interval",
                            type_desc: "string",
                            required: false,
                            description: "Reconciliation interval (default: 5m)",
                            children: &[],
                        },
                        SchemaField {
                            name: "onChange",
                            type_desc: "bool",
                            required: false,
                            description: "Reconcile on file changes (default: false)",
                            children: &[],
                        },
                        SchemaField {
                            name: "autoApply",
                            type_desc: "bool",
                            required: false,
                            description: "Auto-apply on reconcile (default: false)",
                            children: &[],
                        },
                        SchemaField {
                            name: "policy",
                            type_desc: "object",
                            required: false,
                            description: "Auto-apply policy for source updates",
                            children: &[
                                SchemaField {
                                    name: "newRecommended",
                                    type_desc: "string",
                                    required: false,
                                    description: "Action for new recommended items: Notify | Accept | Reject | Ignore (default: Notify)",
                                    children: &[],
                                },
                                SchemaField {
                                    name: "newOptional",
                                    type_desc: "string",
                                    required: false,
                                    description: "Action for new optional items (default: ignore)",
                                    children: &[],
                                },
                                SchemaField {
                                    name: "lockedConflict",
                                    type_desc: "string",
                                    required: false,
                                    description: "Action for locked conflicts (default: Notify)",
                                    children: &[],
                                },
                            ],
                        },
                    ],
                },
                SchemaField {
                    name: "sync",
                    type_desc: "object",
                    required: false,
                    description: "Sync settings for git origin",
                    children: &[
                        SchemaField {
                            name: "autoPush",
                            type_desc: "bool",
                            required: false,
                            description: "Auto-push local changes to remote",
                            children: &[],
                        },
                        SchemaField {
                            name: "autoPull",
                            type_desc: "bool",
                            required: false,
                            description: "Auto-pull remote changes",
                            children: &[],
                        },
                        SchemaField {
                            name: "interval",
                            type_desc: "string",
                            required: false,
                            description: "Sync interval (default: 1h)",
                            children: &[],
                        },
                    ],
                },
                SchemaField {
                    name: "notify",
                    type_desc: "object",
                    required: false,
                    description: "Notification settings",
                    children: &[
                        SchemaField {
                            name: "drift",
                            type_desc: "bool",
                            required: false,
                            description: "Notify on drift detection",
                            children: &[],
                        },
                        SchemaField {
                            name: "method",
                            type_desc: "string",
                            required: false,
                            description: "Notification method: Desktop | Stdout | Webhook (default: Desktop)",
                            children: &[],
                        },
                        SchemaField {
                            name: "webhookUrl",
                            type_desc: "string",
                            required: false,
                            description: "Webhook URL for webhook notifications",
                            children: &[],
                        },
                    ],
                },
            ],
        },
        SchemaField {
            name: "secrets",
            type_desc: "object",
            required: false,
            description: "Secrets backend configuration",
            children: &[
                SchemaField {
                    name: "backend",
                    type_desc: "string",
                    required: false,
                    description: "Secrets backend: sops | age (default: sops)",
                    children: &[],
                },
                SchemaField {
                    name: "sops",
                    type_desc: "object",
                    required: false,
                    description: "SOPS-specific configuration",
                    children: &[SchemaField {
                        name: "ageKey",
                        type_desc: "string",
                        required: false,
                        description: "Path to age key file",
                        children: &[],
                    }],
                },
                SchemaField {
                    name: "integrations",
                    type_desc: "[]object",
                    required: false,
                    description: "External secret provider integrations",
                    children: &[SchemaField {
                        name: "name",
                        type_desc: "string",
                        required: true,
                        description: "Provider name: 1password | bitwarden | vault",
                        children: &[],
                    }],
                },
            ],
        },
        SchemaField {
            name: "sources",
            type_desc: "[]object",
            required: false,
            description: "Multi-source config subscriptions",
            children: &[
                SchemaField {
                    name: "name",
                    type_desc: "string",
                    required: true,
                    description: "Source name",
                    children: &[],
                },
                SchemaField {
                    name: "origin",
                    type_desc: "object",
                    required: true,
                    description: "Source origin (same schema as top-level origin)",
                    children: &[
                        SchemaField {
                            name: "type",
                            type_desc: "string",
                            required: true,
                            description: "Origin type: Git | Server",
                            children: &[],
                        },
                        SchemaField {
                            name: "url",
                            type_desc: "string",
                            required: true,
                            description: "Repository URL or server endpoint",
                            children: &[],
                        },
                        SchemaField {
                            name: "branch",
                            type_desc: "string",
                            required: false,
                            description: "Git branch (default: master)",
                            children: &[],
                        },
                        SchemaField {
                            name: "auth",
                            type_desc: "string",
                            required: false,
                            description: "Auth method for server origins (e.g., device-flow)",
                            children: &[],
                        },
                    ],
                },
                SchemaField {
                    name: "subscription",
                    type_desc: "object",
                    required: false,
                    description: "Subscription preferences",
                    children: &[
                        SchemaField {
                            name: "profile",
                            type_desc: "string",
                            required: false,
                            description: "Profile to subscribe to from the source",
                            children: &[],
                        },
                        SchemaField {
                            name: "priority",
                            type_desc: "integer",
                            required: false,
                            description: "Merge priority (default: 500, local: 1000)",
                            children: &[],
                        },
                        SchemaField {
                            name: "acceptRecommended",
                            type_desc: "bool",
                            required: false,
                            description: "Auto-accept recommended items",
                            children: &[],
                        },
                        SchemaField {
                            name: "optIn",
                            type_desc: "[]string",
                            required: false,
                            description: "Optional items to opt into",
                            children: &[],
                        },
                        SchemaField {
                            name: "overrides",
                            type_desc: "object",
                            required: false,
                            description: "Override values from the source",
                            children: &[],
                        },
                        SchemaField {
                            name: "reject",
                            type_desc: "object",
                            required: false,
                            description: "Reject specific items from the source",
                            children: &[],
                        },
                    ],
                },
                SchemaField {
                    name: "sync",
                    type_desc: "object",
                    required: false,
                    description: "Source sync settings",
                    children: &[
                        SchemaField {
                            name: "interval",
                            type_desc: "string",
                            required: false,
                            description: "Sync interval (default: 1h)",
                            children: &[],
                        },
                        SchemaField {
                            name: "autoApply",
                            type_desc: "bool",
                            required: false,
                            description: "Auto-apply source updates",
                            children: &[],
                        },
                        SchemaField {
                            name: "pinVersion",
                            type_desc: "string",
                            required: false,
                            description: "Pin source to a semver range",
                            children: &[],
                        },
                    ],
                },
            ],
        },
        SchemaField {
            name: "theme",
            type_desc: "string | object",
            required: false,
            description: "Theme name (string) or theme config (object with name + overrides)",
            children: &[
                SchemaField {
                    name: "name",
                    type_desc: "string",
                    required: false,
                    description: "Theme name: default | dracula | solarized-dark | solarized-light | minimal",
                    children: &[],
                },
                SchemaField {
                    name: "overrides",
                    type_desc: "object",
                    required: false,
                    description: "Override individual theme colors and icons",
                    children: &[
                        SchemaField {
                            name: "success",
                            type_desc: "string",
                            required: false,
                            description: "Hex color for success styling (e.g., #50fa7b)",
                            children: &[],
                        },
                        SchemaField {
                            name: "warning",
                            type_desc: "string",
                            required: false,
                            description: "Hex color for warning styling",
                            children: &[],
                        },
                        SchemaField {
                            name: "error",
                            type_desc: "string",
                            required: false,
                            description: "Hex color for error styling",
                            children: &[],
                        },
                        SchemaField {
                            name: "info",
                            type_desc: "string",
                            required: false,
                            description: "Hex color for info styling",
                            children: &[],
                        },
                        SchemaField {
                            name: "muted",
                            type_desc: "string",
                            required: false,
                            description: "Hex color for muted/dim text",
                            children: &[],
                        },
                        SchemaField {
                            name: "header",
                            type_desc: "string",
                            required: false,
                            description: "Hex color for header text",
                            children: &[],
                        },
                        SchemaField {
                            name: "subheader",
                            type_desc: "string",
                            required: false,
                            description: "Hex color for subheader text",
                            children: &[],
                        },
                        SchemaField {
                            name: "key",
                            type_desc: "string",
                            required: false,
                            description: "Hex color for key text in key-value pairs",
                            children: &[],
                        },
                        SchemaField {
                            name: "value",
                            type_desc: "string",
                            required: false,
                            description: "Hex color for value text in key-value pairs",
                            children: &[],
                        },
                        SchemaField {
                            name: "diffAdd",
                            type_desc: "string",
                            required: false,
                            description: "Hex color for diff additions",
                            children: &[],
                        },
                        SchemaField {
                            name: "diffRemove",
                            type_desc: "string",
                            required: false,
                            description: "Hex color for diff removals",
                            children: &[],
                        },
                        SchemaField {
                            name: "diffContext",
                            type_desc: "string",
                            required: false,
                            description: "Hex color for diff context lines",
                            children: &[],
                        },
                        SchemaField {
                            name: "iconSuccess",
                            type_desc: "string",
                            required: false,
                            description: "Custom success icon (default: ✓)",
                            children: &[],
                        },
                        SchemaField {
                            name: "iconWarning",
                            type_desc: "string",
                            required: false,
                            description: "Custom warning icon (default: ⚠)",
                            children: &[],
                        },
                        SchemaField {
                            name: "iconError",
                            type_desc: "string",
                            required: false,
                            description: "Custom error icon (default: ✗)",
                            children: &[],
                        },
                        SchemaField {
                            name: "iconInfo",
                            type_desc: "string",
                            required: false,
                            description: "Custom info icon (default: ●)",
                            children: &[],
                        },
                        SchemaField {
                            name: "iconPending",
                            type_desc: "string",
                            required: false,
                            description: "Custom pending icon (default: ○)",
                            children: &[],
                        },
                        SchemaField {
                            name: "iconArrow",
                            type_desc: "string",
                            required: false,
                            description: "Custom arrow icon (default: →)",
                            children: &[],
                        },
                    ],
                },
            ],
        },
        SchemaField {
            name: "modules",
            type_desc: "object",
            required: false,
            description: "Module configuration: registries and security",
            children: &[
                SchemaField {
                    name: "registries",
                    type_desc: "[]object",
                    required: false,
                    description: "Module registries — searchable indexes of reusable modules",
                    children: &[
                        SchemaField {
                            name: "name",
                            type_desc: "string",
                            required: true,
                            description: "Short name/alias for this registry",
                            children: &[],
                        },
                        SchemaField {
                            name: "url",
                            type_desc: "string",
                            required: true,
                            description: "Git URL of the registry repository",
                            children: &[],
                        },
                    ],
                },
                SchemaField {
                    name: "security",
                    type_desc: "object",
                    required: false,
                    description: "Module security settings",
                    children: &[SchemaField {
                        name: "requireSignatures",
                        type_desc: "bool",
                        required: false,
                        description: "Require GPG/SSH signatures on remote module tags (default: false)",
                        children: &[],
                    }],
                },
            ],
        },
    ],
};
