use super::{ResourceSchema, SchemaField};

pub(super) static SCHEMA_PROFILE: ResourceSchema = ResourceSchema {
    name: "Profile",
    api_version: cfgd_core::API_VERSION,
    kind: "Profile",
    location: "profiles/<name>.yaml",
    description: "Defines the desired state for a machine: packages, files, system settings, secrets, and scripts. Supports inheritance for layered configuration.",
    fields: &[
        SchemaField {
            name: "inherits",
            type_desc: "[]string",
            required: false,
            description: "Ordered list of parent profiles (later overrides earlier)",
            children: &[],
        },
        SchemaField {
            name: "modules",
            type_desc: "[]string",
            required: false,
            description: "Modules to include (local names or registry/module references)",
            children: &[],
        },
        SchemaField {
            name: "env",
            type_desc: "list[{name, value}]",
            required: false,
            description: "Environment variables (name/value pairs) available in templates and written to ~/.cfgd.env",
            children: &[],
        },
        SchemaField {
            name: "aliases",
            type_desc: "list[{name, command}]",
            required: false,
            description: "Shell aliases written to ~/.cfgd.env as `alias name=\"command\"` (fish: `abbr -a name command`)",
            children: &[],
        },
        SchemaField {
            name: "packages",
            type_desc: "object",
            required: false,
            description: "Package declarations by manager",
            children: &[
                SchemaField {
                    name: "brew",
                    type_desc: "object",
                    required: false,
                    description: "Homebrew packages",
                    children: &[
                        SchemaField {
                            name: "file",
                            type_desc: "string",
                            required: false,
                            description: "Path to Brewfile (relative to config repo root)",
                            children: &[],
                        },
                        SchemaField {
                            name: "taps",
                            type_desc: "[]string",
                            required: false,
                            description: "Homebrew taps to add",
                            children: &[],
                        },
                        SchemaField {
                            name: "formulae",
                            type_desc: "[]string",
                            required: false,
                            description: "Homebrew formulae to install",
                            children: &[],
                        },
                        SchemaField {
                            name: "casks",
                            type_desc: "[]string",
                            required: false,
                            description: "Homebrew casks to install",
                            children: &[],
                        },
                    ],
                },
                SchemaField {
                    name: "apt",
                    type_desc: "object",
                    required: false,
                    description: "APT packages (Debian/Ubuntu)",
                    children: &[
                        SchemaField {
                            name: "file",
                            type_desc: "string",
                            required: false,
                            description: "Path to package list file (one per line)",
                            children: &[],
                        },
                        SchemaField {
                            name: "packages",
                            type_desc: "[]string",
                            required: false,
                            description: "Packages to install",
                            children: &[],
                        },
                    ],
                },
                SchemaField {
                    name: "cargo",
                    type_desc: "[]string | object",
                    required: false,
                    description: "Cargo/Rust packages",
                    children: &[
                        SchemaField {
                            name: "file",
                            type_desc: "string",
                            required: false,
                            description: "Path to Cargo.toml to read dependencies from",
                            children: &[],
                        },
                        SchemaField {
                            name: "packages",
                            type_desc: "[]string",
                            required: false,
                            description: "Packages to install",
                            children: &[],
                        },
                    ],
                },
                SchemaField {
                    name: "npm",
                    type_desc: "object",
                    required: false,
                    description: "NPM global packages",
                    children: &[
                        SchemaField {
                            name: "file",
                            type_desc: "string",
                            required: false,
                            description: "Path to package.json",
                            children: &[],
                        },
                        SchemaField {
                            name: "global",
                            type_desc: "[]string",
                            required: false,
                            description: "Global packages to install",
                            children: &[],
                        },
                    ],
                },
                SchemaField {
                    name: "pipx",
                    type_desc: "[]string",
                    required: false,
                    description: "pipx Python packages",
                    children: &[],
                },
                SchemaField {
                    name: "dnf",
                    type_desc: "[]string",
                    required: false,
                    description: "DNF packages (Fedora/RHEL)",
                    children: &[],
                },
                SchemaField {
                    name: "apk",
                    type_desc: "[]string",
                    required: false,
                    description: "APK packages (Alpine)",
                    children: &[],
                },
                SchemaField {
                    name: "pacman",
                    type_desc: "[]string",
                    required: false,
                    description: "Pacman packages (Arch/Manjaro)",
                    children: &[],
                },
                SchemaField {
                    name: "zypper",
                    type_desc: "[]string",
                    required: false,
                    description: "Zypper packages (openSUSE/SLES)",
                    children: &[],
                },
                SchemaField {
                    name: "yum",
                    type_desc: "[]string",
                    required: false,
                    description: "Yum packages (RHEL 7/CentOS 7)",
                    children: &[],
                },
                SchemaField {
                    name: "pkg",
                    type_desc: "[]string",
                    required: false,
                    description: "pkg packages (FreeBSD)",
                    children: &[],
                },
                SchemaField {
                    name: "snap",
                    type_desc: "object",
                    required: false,
                    description: "Snap packages (Ubuntu)",
                    children: &[
                        SchemaField {
                            name: "packages",
                            type_desc: "[]string",
                            required: false,
                            description: "Snap packages to install",
                            children: &[],
                        },
                        SchemaField {
                            name: "classic",
                            type_desc: "[]string",
                            required: false,
                            description: "Snap packages to install with --classic",
                            children: &[],
                        },
                    ],
                },
                SchemaField {
                    name: "flatpak",
                    type_desc: "object",
                    required: false,
                    description: "Flatpak packages",
                    children: &[
                        SchemaField {
                            name: "packages",
                            type_desc: "[]string",
                            required: false,
                            description: "Flatpak app IDs (reverse-DNS)",
                            children: &[],
                        },
                        SchemaField {
                            name: "remote",
                            type_desc: "string",
                            required: false,
                            description: "Flatpak remote (default: flathub)",
                            children: &[],
                        },
                    ],
                },
                SchemaField {
                    name: "nix",
                    type_desc: "[]string",
                    required: false,
                    description: "Nix packages",
                    children: &[],
                },
                SchemaField {
                    name: "go",
                    type_desc: "[]string",
                    required: false,
                    description: "Go packages (go install)",
                    children: &[],
                },
                SchemaField {
                    name: "winget",
                    type_desc: "[]string",
                    required: false,
                    description: "Windows Package Manager (winget) packages by ID (Windows only)",
                    children: &[],
                },
                SchemaField {
                    name: "chocolatey",
                    type_desc: "[]string",
                    required: false,
                    description: "Chocolatey packages (Windows only)",
                    children: &[],
                },
                SchemaField {
                    name: "scoop",
                    type_desc: "[]string",
                    required: false,
                    description: "Scoop packages (Windows only)",
                    children: &[],
                },
                SchemaField {
                    name: "custom",
                    type_desc: "[]object",
                    required: false,
                    description: "User-defined package managers",
                    children: &[
                        SchemaField {
                            name: "name",
                            type_desc: "string",
                            required: true,
                            description: "Manager name",
                            children: &[],
                        },
                        SchemaField {
                            name: "check",
                            type_desc: "string",
                            required: true,
                            description: "Shell command to check availability",
                            children: &[],
                        },
                        SchemaField {
                            name: "listInstalled",
                            type_desc: "string",
                            required: true,
                            description: "Shell command to list installed packages (one per line)",
                            children: &[],
                        },
                        SchemaField {
                            name: "install",
                            type_desc: "string",
                            required: true,
                            description: "Shell command template to install ({packages} or {package})",
                            children: &[],
                        },
                        SchemaField {
                            name: "uninstall",
                            type_desc: "string",
                            required: true,
                            description: "Shell command template to uninstall",
                            children: &[],
                        },
                        SchemaField {
                            name: "update",
                            type_desc: "string",
                            required: false,
                            description: "Shell command to update all packages",
                            children: &[],
                        },
                        SchemaField {
                            name: "packages",
                            type_desc: "[]string",
                            required: false,
                            description: "Packages to manage",
                            children: &[],
                        },
                    ],
                },
            ],
        },
        SchemaField {
            name: "files",
            type_desc: "object",
            required: false,
            description: "File management declarations",
            children: &[
                SchemaField {
                    name: "managed",
                    type_desc: "[]object",
                    required: false,
                    description: "Files to manage",
                    children: &[
                        SchemaField {
                            name: "source",
                            type_desc: "string",
                            required: true,
                            description: "Relative path in source repo",
                            children: &[],
                        },
                        SchemaField {
                            name: "target",
                            type_desc: "string",
                            required: true,
                            description: "Absolute target path on the machine",
                            children: &[],
                        },
                    ],
                },
                SchemaField {
                    name: "permissions",
                    type_desc: "map[string]string",
                    required: false,
                    description: "Permission overrides by path (e.g., \".ssh/config\": \"600\")",
                    children: &[],
                },
            ],
        },
        SchemaField {
            name: "system",
            type_desc: "map[string]any",
            required: false,
            description: "System configurator settings (keys map to registered configurators)",
            children: &[
                SchemaField {
                    name: "shell",
                    type_desc: "string",
                    required: false,
                    description: "Default shell path (e.g., /bin/zsh)",
                    children: &[],
                },
                SchemaField {
                    name: "macosDefaults",
                    type_desc: "map[string]map",
                    required: false,
                    description: "macOS defaults by domain and key",
                    children: &[],
                },
                SchemaField {
                    name: "launchAgents",
                    type_desc: "[]object",
                    required: false,
                    description: "macOS LaunchAgent definitions",
                    children: &[],
                },
                SchemaField {
                    name: "systemdUnits",
                    type_desc: "[]object",
                    required: false,
                    description: "systemd unit file management",
                    children: &[],
                },
                SchemaField {
                    name: "gsettings",
                    type_desc: "map[string]map",
                    required: false,
                    description: "GNOME/GTK desktop settings by schema and key (Linux)",
                    children: &[],
                },
                SchemaField {
                    name: "kdeConfig",
                    type_desc: "map[string]map[string]map",
                    required: false,
                    description: "KDE Plasma settings by file, group, and key (Linux)",
                    children: &[],
                },
                SchemaField {
                    name: "xfconf",
                    type_desc: "map[string]map",
                    required: false,
                    description: "XFCE desktop settings by channel and property (Linux)",
                    children: &[],
                },
                SchemaField {
                    name: "environment",
                    type_desc: "map[string]string",
                    required: false,
                    description: "Environment variable declarations",
                    children: &[],
                },
                SchemaField {
                    name: "sysctl",
                    type_desc: "map[string]any",
                    required: false,
                    description: "Kernel parameters (Linux nodes)",
                    children: &[],
                },
                SchemaField {
                    name: "kernelModules",
                    type_desc: "[]string",
                    required: false,
                    description: "Kernel modules to load (Linux nodes)",
                    children: &[],
                },
                SchemaField {
                    name: "containerd",
                    type_desc: "object",
                    required: false,
                    description: "containerd configuration (k8s nodes)",
                    children: &[],
                },
                SchemaField {
                    name: "kubelet",
                    type_desc: "object",
                    required: false,
                    description: "kubelet configuration (k8s nodes)",
                    children: &[],
                },
                SchemaField {
                    name: "windowsRegistry",
                    type_desc: "map[string]map",
                    required: false,
                    description: "Windows registry settings (Windows only). Keys are registry paths, values are name-value maps",
                    children: &[],
                },
                SchemaField {
                    name: "windowsServices",
                    type_desc: "[]object",
                    required: false,
                    description: "Windows Service management (Windows only). Each entry has name, binaryPath, startType, state",
                    children: &[],
                },
            ],
        },
        SchemaField {
            name: "secrets",
            type_desc: "[]object",
            required: false,
            description: "Secret file declarations",
            children: &[
                SchemaField {
                    name: "source",
                    type_desc: "string",
                    required: true,
                    description: "Path to SOPS-encrypted file or provider://ref",
                    children: &[],
                },
                SchemaField {
                    name: "target",
                    type_desc: "string",
                    required: true,
                    description: "Target path for decrypted output",
                    children: &[],
                },
                SchemaField {
                    name: "template",
                    type_desc: "string",
                    required: false,
                    description: "Template string to inject secret into",
                    children: &[],
                },
                SchemaField {
                    name: "backend",
                    type_desc: "string",
                    required: false,
                    description: "Override secrets backend: sops | age",
                    children: &[],
                },
            ],
        },
        SchemaField {
            name: "scripts",
            type_desc: "object",
            required: false,
            description: "Lifecycle scripts",
            children: &[
                SchemaField {
                    name: "preReconcile",
                    type_desc: "[]string",
                    required: false,
                    description: "Scripts to run before reconciliation",
                    children: &[],
                },
                SchemaField {
                    name: "postReconcile",
                    type_desc: "[]string",
                    required: false,
                    description: "Scripts to run after reconciliation",
                    children: &[],
                },
            ],
        },
    ],
};
