apiVersion: v2
name: cfgd
description: cfgd Kubernetes DaemonSet agent for node-level configuration management
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - node-config
  - gitops
  - daemonset
  - kubernetes
home: https://github.com/tj-smith47/cfgd
maintainers:
  - name: cfgd
    url: https://github.com/tj-smith47/cfgd
